# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy Web Server

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - hardware_web_server/**

jobs:
  deploy_server:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Server
        uses: easingthemes/ssh-deploy@v2.2.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TENGXUN_TOKEN }}
          ARGS: "-avzr --delete"
          SOURCE: "hardware_web_server/app"
          REMOTE_HOST: ${{ secrets.TENGXUN_HOST }}
          REMOTE_USER: "root"
          TARGET: "/home/root/hardware/hardware_web_server/"
      
      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENGXUN_HOST }}
          username: "root"
          key: ${{ secrets.TENGXUN_TOKEN }}
          script: |
            cd /home/root/hardware_web_server
            docker-compose restart

